{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"snowball_output\",\"customer\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "customer": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "customer"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "buyer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "patron": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "purchaser": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "shopper": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "customer.customer_country": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "customer",
                    "ConceptualProperty": "customer_country"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer country": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer country": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "customer_country": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "country": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "country": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "customer nation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "customer location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "nation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "client country": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer country": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user country": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer country": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron country": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchaser country": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "customer.customer_id": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "customer",
                    "ConceptualProperty": "customer_id"
                  }
                },
                "NameType": "Identifier",
                "State": "Generated",
                "Terms": [
                  {
                    "customer id": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer id": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "id": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "id": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "customer_id": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "customer identification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "customer identity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "customer identifier": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "customer credential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "client id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchaser id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "customer.customer_key": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "customer",
                    "ConceptualProperty": "customer_key"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer key": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer key": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "customer_key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "client key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchaser key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "shopper key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "main": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "basic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fundamental": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "customer.customer_name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "customer",
                    "ConceptualProperty": "customer_name"
                  }
                },
                "NameType": "Name",
                "State": "Generated",
                "Terms": [
                  {
                    "customer name": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer name": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "name": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "name": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "customer_name": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "customer nickname": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer title": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer label": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer surname": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "client name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "customer.customer_region": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "customer",
                    "ConceptualProperty": "customer_region "
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer region": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer region": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "customer_region ": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "region": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "region": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "customer_region": {
                      "State": "Generated",
                      "Weight": 0.96029999999999993
                    }
                  },
                  {
                    "customer_region": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.96029999999999993
                    }
                  },
                  {
                    "customer location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  },
                  {
                    "location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.818
                    }
                  },
                  {
                    "customer province": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "province": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "customer area": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer district": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer section": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer zone": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer continent": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "area": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "customer.dimension_1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "customer",
                    "ConceptualProperty": "dimension_1"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dimension 1": {
                      "State": "Generated"
                    }
                  },
                  {
                    "dimension 1": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "dimension_1": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "snowball_output": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "snowball output": {
                      "State": "Generated"
                    }
                  },
                  {
                    "snowball output": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "snowball_output": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "output": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "output": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "snowball production": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "snowball productivity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "production": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "productivity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "snowball yield": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "snowball harvest": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "snowball crop": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "yield": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "harvest": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "crop": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "snowball_output.bop_arr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "bop_arr"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "bop arr": {
                      "State": "Generated"
                    }
                  },
                  {
                    "bop arr": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "bop_arr": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "snowball_output.cross_sell": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "cross_sell"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "cross sell": {
                      "State": "Generated"
                    }
                  },
                  {
                    "cross sell": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "cross_sell": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "sell": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "sell": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "symbol sell": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "mark sell": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "sign sell": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  }
                ]
              },
              "snowball_output.customer_churn": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "customer_churn"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer churn": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer churn": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "customer_churn": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "churn": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "churn": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "client churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchaser churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "shopper churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "snowball_output.customer_key": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "customer_key"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer key": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer key": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "customer_key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "client key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchaser key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "shopper key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "main": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "basic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fundamental": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "snowball_output.downsell": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "downsell"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "downsell": {
                      "State": "Generated"
                    }
                  },
                  {
                    "downsell": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  }
                ]
              },
              "snowball_output.eop_arr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "eop_arr"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "eop arr": {
                      "State": "Generated"
                    }
                  },
                  {
                    "eop arr": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "eop_arr": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "snowball_output.grr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "grr"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "grr": {
                      "State": "Generated"
                    }
                  },
                  {
                    "grr": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  }
                ]
              },
              "snowball_output.measure_average_churn": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "Measure Average Churn"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "measure average churn": {
                      "State": "Generated"
                    }
                  },
                  {
                    "measure average churn": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "churn": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "churn": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "average churn": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "average churn": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "snowball_output.month_roll": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "month_roll"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month roll": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month roll": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "month_roll": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.7
                    }
                  },
                  {
                    "roll": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "roll": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "mth roll": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "month reel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "month cylinder": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "month spool": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "month tube": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "reel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "cylinder": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "spool": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "tube": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "snowball_output.month_roll.variation.date_hierarchy": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "Hierarchy": "Date Hierarchy",
                    "VariationSet": "Variation",
                    "VariationSource": "month_roll"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month roll date hierarchy": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month roll date hierarchy": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "date hierarchy": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "roll date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "roll date hierarchy": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "snowball_output.month_roll.variation.date_hierarchy.day": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Day",
                    "VariationSet": "Variation",
                    "VariationSource": "month_roll"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month roll day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month roll day": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "day": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "roll day": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "roll day": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "mth roll day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  }
                ]
              },
              "snowball_output.month_roll.variation.date_hierarchy.month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Month",
                    "VariationSet": "Variation",
                    "VariationSource": "month_roll"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month roll month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month roll month": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "roll month": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "roll month": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "month roll mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "roll mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "mth roll month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  }
                ]
              },
              "snowball_output.month_roll.variation.date_hierarchy.quarter": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Quarter",
                    "VariationSet": "Variation",
                    "VariationSource": "month_roll"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month roll quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month roll quarter": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "quarter": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "roll quarter": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "roll quarter": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "month roll qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.846
                    }
                  },
                  {
                    "roll qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  },
                  {
                    "qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.818
                    }
                  },
                  {
                    "mth roll quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  }
                ]
              },
              "snowball_output.month_roll.variation.date_hierarchy.year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Year",
                    "VariationSet": "Variation",
                    "VariationSource": "month_roll"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month roll year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month roll year": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "year": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "roll year": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "roll year": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "month roll yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "roll yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "mth roll year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  }
                ]
              },
              "snowball_output.new_customer": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "new_customer"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "new customer": {
                      "State": "Generated"
                    }
                  },
                  {
                    "new customer": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "new_customer": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "new client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new buyer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new patron": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new purchaser": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new shopper": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  }
                ]
              },
              "snowball_output.nrr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "nrr"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "nrr": {
                      "State": "Generated"
                    }
                  },
                  {
                    "nrr": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  }
                ]
              },
              "snowball_output.period_type": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "period_type"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "period type": {
                      "State": "Generated"
                    }
                  },
                  {
                    "period type": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "period_type": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "type": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "type": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "period category": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "period genre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "period manner": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "period variety": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "category": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "genre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "manner": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "variety": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "period brand": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "period class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "snowball_output.product_churn": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "product_churn"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "product churn": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product churn": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "product_churn": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "churn": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "churn": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "artifact churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "item churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "merchandise churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "produce churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "snowball_output.product_key": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "product_key"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "product key": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product key": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "product_key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "artifact key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "item key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "merchandise key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "produce key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "main": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "basic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fundamental": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "central": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "major": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "keynote": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "snowball_output.snowball_key": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "snowball_key"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "snowball key": {
                      "State": "Generated"
                    }
                  },
                  {
                    "snowball key": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "snowball_key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "main": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "basic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fundamental": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "central": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "major": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "keynote": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "essential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "snowball solution": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "snowball explanation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "snowball basis": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  }
                ]
              },
              "snowball_output.upsell": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "upsell"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "upsell": {
                      "State": "Generated"
                    }
                  },
                  {
                    "upsell": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "customer_has_customer_country": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "customer.customer_country"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "ID": "customers_have_customer_countries",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_country": {
                    "Target": {
                      "Entity": "customer.customer_country"
                    }
                  }
                },
                "State": "Generated"
              },
              "customer_has_customer_id": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "customer.customer_id"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "ID": "customers_have_customer_ids",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "customer_ids_are_names_IDs_of_customers",
                    "Name": {
                      "Name": {
                        "Role": "customer.customer_id"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_id": {
                    "Target": {
                      "Entity": "customer.customer_id"
                    }
                  }
                },
                "State": "Generated"
              },
              "customer_has_customer_key": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "customer.customer_key"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "ID": "customers_have_customer_keys",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_key": {
                    "Target": {
                      "Entity": "customer.customer_key"
                    }
                  }
                },
                "State": "Generated"
              },
              "customer_has_customer_name": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "customer.customer_name"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "ID": "customers_have_customer_names",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "customer_names_are_names_IDs_of_customers",
                    "Name": {
                      "Name": {
                        "Role": "customer.customer_name"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_name": {
                    "Target": {
                      "Entity": "customer.customer_name"
                    }
                  }
                },
                "State": "Generated"
              },
              "customer_has_customer_region": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "customer.customer_region"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "ID": "customers_have_customer_regions",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_region": {
                    "Target": {
                      "Entity": "customer.customer_region"
                    }
                  }
                },
                "State": "Generated"
              },
              "customer_has_dimension_1": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "customer.dimension_1"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "ID": "customers_have_dimension_1",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.dimension_1": {
                    "Target": {
                      "Entity": "customer.dimension_1"
                    }
                  }
                },
                "State": "Generated"
              },
              "customer_in_customer_country": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "ID": "customers_are_in_customer_countries",
                    "Preposition": {
                      "Object": {
                        "Role": "customer.customer_country"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_country": {
                    "Target": {
                      "Entity": "customer.customer_country"
                    }
                  }
                },
                "SemanticSlots": {
                  "Where": {
                    "Role": "customer.customer_country"
                  }
                },
                "State": "Generated"
              },
              "customer_in_customer_region": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "ID": "customers_are_in_customer_regions",
                    "Preposition": {
                      "Object": {
                        "Role": "customer.customer_region"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_region": {
                    "Target": {
                      "Entity": "customer.customer_region"
                    }
                  }
                },
                "SemanticSlots": {
                  "Where": {
                    "Role": "customer.customer_region"
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_bop_arr": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.bop_arr"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_bop_arrs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.bop_arr": {
                    "Target": {
                      "Entity": "snowball_output.bop_arr"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_cross_sell": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.cross_sell"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_cross_sell",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.cross_sell": {
                    "Target": {
                      "Entity": "snowball_output.cross_sell"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_customer": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "customer"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_customers",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "ID": "customers_have_snowball_outputs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_customer_churn": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.customer_churn"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_customer_churns",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.customer_churn": {
                    "Target": {
                      "Entity": "snowball_output.customer_churn"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_downsell": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.downsell"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_downsells",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.downsell": {
                    "Target": {
                      "Entity": "snowball_output.downsell"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_eop_arr": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.eop_arr"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_eop_arrs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.eop_arr": {
                    "Target": {
                      "Entity": "snowball_output.eop_arr"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_grr": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.grr"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_grrs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.grr": {
                    "Target": {
                      "Entity": "snowball_output.grr"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_measure_average_churn": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.measure_average_churn"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_measure_average_churn",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.measure_average_churn": {
                    "Target": {
                      "Entity": "snowball_output.measure_average_churn"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_month_roll": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month_roll"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_month_rolls",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.month_roll": {
                    "Target": {
                      "Entity": "snowball_output.month_roll"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_new_customer": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.new_customer"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_new_customers",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.new_customer": {
                    "Target": {
                      "Entity": "snowball_output.new_customer"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_nrr": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.nrr"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_nrrs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.nrr": {
                    "Target": {
                      "Entity": "snowball_output.nrr"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_period_type": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.period_type"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_period_types",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.period_type": {
                    "Target": {
                      "Entity": "snowball_output.period_type"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_product_churn": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.product_churn"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_product_churns",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.product_churn": {
                    "Target": {
                      "Entity": "snowball_output.product_churn"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_product_key": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.product_key"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_product_keys",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.product_key": {
                    "Target": {
                      "Entity": "snowball_output.product_key"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_snowball_key": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.snowball_key"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_snowball_keys",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.snowball_key": {
                    "Target": {
                      "Entity": "snowball_output.snowball_key"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_upsell": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.upsell"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_upsell",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.upsell": {
                    "Target": {
                      "Entity": "snowball_output.upsell"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_month_roll_has_variation_date_hierarchy": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy"
                      },
                      "Subject": {
                        "Role": "snowball_output.month_roll"
                      }
                    },
                    "ID": "month_rolls_have_month_roll_date_hierarchies",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output.month_roll": {
                    "Target": {
                      "Entity": "snowball_output.month_roll"
                    }
                  },
                  "snowball_output.month_roll.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_month_roll_variation_date_hierarchy_has_day": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy.day"
                      },
                      "Subject": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy"
                      }
                    },
                    "ID": "month_roll_date_hierarchies_have_month_roll_days",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output.month_roll.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy"
                    }
                  },
                  "snowball_output.month_roll.variation.date_hierarchy.day": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy.day"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_month_roll_variation_date_hierarchy_has_month": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy.month"
                      },
                      "Subject": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy"
                      }
                    },
                    "ID": "month_roll_date_hierarchies_have_month_roll_months",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output.month_roll.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy"
                    }
                  },
                  "snowball_output.month_roll.variation.date_hierarchy.month": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy.month"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_month_roll_variation_date_hierarchy_has_quarter": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy.quarter"
                      },
                      "Subject": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy"
                      }
                    },
                    "ID": "month_roll_date_hierarchies_have_month_roll_quarters",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output.month_roll.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy"
                    }
                  },
                  "snowball_output.month_roll.variation.date_hierarchy.quarter": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy.quarter"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_month_roll_variation_date_hierarchy_has_year": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy.year"
                      },
                      "Subject": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy"
                      }
                    },
                    "ID": "month_roll_date_hierarchies_have_month_roll_years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output.month_roll.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy"
                    }
                  },
                  "snowball_output.month_roll.variation.date_hierarchy.year": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy.year"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "9cd7c8be-4c50-4121-abf3-14cf73f50185",
        "fromColumn": "month_roll",
        "fromTable": "snowball_output",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f2e916b0-79af-4076-b66d-9e15cc4cc4b2"
      },
      {
        "name": "AutoDetected_39b1a03e-16ab-4aef-a866-a63af60fd194",
        "fromColumn": "customer_key",
        "fromTable": "snowball_output",
        "toColumn": "customer_key",
        "toTable": "customer"
      }
    ],
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "snowball_output",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "snowball_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "640beed4-cfa0-447d-9509-f08ddec56b14",
            "sourceColumn": "snowball_key",
            "summarizeBy": "none"
          },
          {
            "name": "customer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77bd386b-ed4f-450b-b625-c04039b01e48",
            "sourceColumn": "customer_key",
            "summarizeBy": "none"
          },
          {
            "name": "product_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf248224-6558-4d1f-8514-091e419a1bd3",
            "sourceColumn": "product_key",
            "summarizeBy": "none"
          },
          {
            "name": "month_roll",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "57847788-ba89-4750-b95b-057cea0a0553",
            "sourceColumn": "month_roll",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_f2e916b0-79af-4076-b66d-9e15cc4cc4b2"
                },
                "isDefault": true,
                "relationship": "9cd7c8be-4c50-4121-abf3-14cf73f50185"
              }
            ]
          },
          {
            "name": "period_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3e81335-99a4-4805-acb4-549b3e21f768",
            "sourceColumn": "period_type",
            "summarizeBy": "none"
          },
          {
            "name": "bop_arr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4cfa6662-2f44-4f4e-9bd0-f6d584e4d020",
            "sourceColumn": "bop_arr",
            "summarizeBy": "sum"
          },
          {
            "name": "customer_churn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bc2cd3b8-4266-43b7-ab3d-36e66ad857fb",
            "sourceColumn": "customer_churn",
            "summarizeBy": "sum"
          },
          {
            "name": "product_churn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cd926218-eba3-47ac-9f07-4651120dbd6f",
            "sourceColumn": "product_churn",
            "summarizeBy": "sum"
          },
          {
            "name": "downsell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9d49d6a1-bc39-48d7-b570-61f5fa476303",
            "sourceColumn": "downsell",
            "summarizeBy": "sum"
          },
          {
            "name": "grr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4cd9a903-dc89-429d-925e-afe9016a5a37",
            "sourceColumn": "grr",
            "summarizeBy": "sum"
          },
          {
            "name": "upsell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1f4cb64b-1aeb-4151-a9b0-3c25cc88fb4a",
            "sourceColumn": "upsell",
            "summarizeBy": "sum"
          },
          {
            "name": "cross_sell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "35aa644f-50fa-4568-8bee-053b2cdbe771",
            "sourceColumn": "cross_sell",
            "summarizeBy": "sum"
          },
          {
            "name": "nrr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4a8f7e87-6e58-4bf4-a21a-ba77581a6fae",
            "sourceColumn": "nrr",
            "summarizeBy": "sum"
          },
          {
            "name": "new_customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e7fd3422-5058-4902-a986-f80672605a45",
            "sourceColumn": "new_customer",
            "summarizeBy": "sum"
          },
          {
            "name": "eop_arr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4cf64132-e033-4275-8d0a-c5db0f996b70",
            "sourceColumn": "eop_arr",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "50b9ef88-c14b-4f4b-b329-766f7c8ae653",
        "measures": [
          {
            "name": "Measure Average Churn",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(snowball_output[customer_churn]) + AVERAGE(snowball_output[product_churn])",
            "lineageTag": "751f9635-5de6-49b4-bee8-f292a67da376"
          }
        ],
        "partitions": [
          {
            "name": "snowball_output",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\HarshVerma\\Downloads\\snowball_output.csv\"),[Delimiter=\",\", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"snowball_key\", type text}, {\"customer_key\", type text}, {\"product_key\", type text}, {\"month_roll\", type date}, {\"period_type\", type text}, {\"bop_arr\", type number}, {\"customer_churn\", type number}, {\"product_churn\", type number}, {\"downsell\", type number}, {\"grr\", type number}, {\"upsell\", type number}, {\"cross_sell\", Int64.Type}, {\"nrr\", type number}, {\"new_customer\", type number}, {\"eop_arr\", type number}}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Changed Type\",{{\"month_roll\", Order.Descending}})",
                "in",
                "    #\"Sorted Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_9b8e5eca-b244-479f-9139-5969c60a1266",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0f26bd32-2fcd-4c24-9f70-eb263471bd24",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "61f1700a-f8c9-41b9-8055-349286ac6333",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "034456fb-a2d3-44af-bdbc-883774837c7d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "eb206094-2695-4977-9087-68ab1718b8a8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "21596fb3-fdcd-4f07-b341-6042fcc56073",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "34b4e1a3-932a-4a0b-863b-157b89eebfab",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "63a4f50c-ff51-48b1-b2d9-100238ef7220",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "69875c80-3925-4827-8b70-46c0c5cd050e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "5fe12bad-3ac0-405f-bf36-c82c61063c53",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "507f0860-34c7-4f2d-8ea1-6f9a9f00125e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e2012b95-5209-418a-88e6-30c4b5a0aa2f",
                "ordinal": 3
              }
            ],
            "lineageTag": "f006d905-b2b6-48f4-8cdd-d169def32cd0"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "05ca4316-da61-4f90-8a60-299079ddb753",
        "partitions": [
          {
            "name": "DateTableTemplate_9b8e5eca-b244-479f-9139-5969c60a1266",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_f2e916b0-79af-4076-b66d-9e15cc4cc4b2",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "15da47bf-85e5-4395-9ba8-aaac59e46ad9",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c9a09065-048b-4dd5-a77e-1d1fec4de464",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8a84dac1-8af7-48c1-a184-dcf7a6af61dd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ea7488f9-f84b-4ef9-84a0-c5a6db000eee",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d45ee37a-7f6e-4744-a5e4-e23229bb8169",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "485e74be-b341-4ebe-aade-a21573cd531e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9d8b652d-2771-4d0f-9a66-2afb016108c1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "8a944411-4234-4772-893a-d1f1765d3ce6",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "261e0eb1-55e7-4e36-aa47-0371e07ed03f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "4df7e33f-7849-4970-a26a-04bcfac46a09",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "92d971aa-834f-4f8e-9bf9-0b47718237cc",
                "ordinal": 3
              }
            ],
            "lineageTag": "687d6435-dd1b-4b99-acc9-793fada4bfbb"
          }
        ],
        "isHidden": true,
        "lineageTag": "c20cfe44-4f35-4afc-adfb-dbddb0cadaad",
        "partitions": [
          {
            "name": "LocalDateTable_f2e916b0-79af-4076-b66d-9e15cc4cc4b2",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('snowball_output'[month_roll])), 1, 1), Date(Year(MAX('snowball_output'[month_roll])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "customer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "customer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fca7dc37-7136-4033-ae6d-3c118328a7be",
            "sourceColumn": "customer_key",
            "summarizeBy": "none"
          },
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4c997fa4-4bf9-42ea-bf17-16d60feb06d5",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "customer_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9c3d687-5af8-4a9a-97e2-6dd71adb7fa8",
            "sourceColumn": "customer_name",
            "summarizeBy": "none"
          },
          {
            "name": "customer_country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e9acd09-89b4-4fb3-8391-8e4b0cf89d9f",
            "sourceColumn": "customer_country",
            "summarizeBy": "none"
          },
          {
            "name": "customer_region ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f3c9648-d03d-4b9b-aef3-cbcde25a267e",
            "sourceColumn": "customer_region ",
            "summarizeBy": "none"
          },
          {
            "name": "dimension_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1a75f9b-dfcd-4e4a-b99f-6707d09d9dd9",
            "sourceColumn": "dimension_1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f1b9492f-312e-46d7-90cc-759c84276bc1",
        "partitions": [
          {
            "name": "customer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\HarshVerma\\Downloads\\customer.csv\"),[Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"customer_key\", type text}, {\"customer_id\", Int64.Type}, {\"customer_name\", type text}, {\"customer_country\", type text}, {\"customer_region \", type text}, {\"dimension_1\", type text}}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Changed Type\",{{\"customer_region \", Order.Ascending}})",
                "in",
                "    #\"Sorted Rows\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}